In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
path = "C:\\datasets\\spe\\World Bank Carbon Pricing.xlsx"
df = pd.read_excel(path, sheet_name='Compliance_Price', skiprows=1)

In [17]:
first_cols_df = df[['Name of the initiative', 'Instrument Type', 'Jurisdiction Covered', 'Region', 'Income group']]
price_cols_df = df.iloc[:, 35:]
temp_df = pd.concat([first_cols_df, price_cols_df], axis=1)
temp_df.to_csv("temp_price.csv", index=False)
temp_df

,Name of the initiative,Instrument Type,Jurisdiction Covered,Region,Income group,2017,2018,2019,2020,2021,2022,2023,2024
0,Albania Carbon tax,Carbon tax,Albania,Europe & Central Asia,Upper middle income,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.111355
1,Alberta carbon tax,Carbon tax,Alberta,North America,High income,15.026357,23.252205,22.493795,NaN,NaN,NaN,NaN,NaN
2,Alberta TIER,ETS,Alberta,North America,High income,22.539536,23.252205,22.493795,21.101497,31.834461,39.961637,48.030740,58.944887
3,Argentina carbon tax,Carbon tax,Argentina,Latin America & Caribbean,Upper middle income,NaN,8.914348,6.187569,6.342015,5.321599,4.995626,3.338991,0.811554
4,Argentina carbon tax,Carbon tax,Argentina,Latin America & Caribbean,Upper middle income,NaN,10.129136,7.030770,7.206262,6.457344,8.568062,7.585637,4.393625
...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,Ukraine carbon tax,Carbon tax,Ukraine,Europe & Central Asia,Lower middle income,0.013668,0.015443,0.368369,0.384615,0.359420,1.025469,0.820376,0.767756
138,Uruguay CO2 tax,Carbon tax,Uruguay,Latin America & Caribbean,High income,NaN,NaN,NaN,NaN,NaN,137.295411,155.868350,167.173810
139,Washington CCA,ETS,Washington,North America,High income,NaN,NaN,NaN,NaN,NaN,NaN,22.200000,25.750000
140,Yucatan carbon tax,Carbon tax,Yucatan,Latin America & Caribbean,Upper middle income,NaN,NaN,NaN,NaN,NaN,NaN,15.525317,17.693831
141,Zacatecas carbon tax,Carbon tax,Zacatecas,Latin America & Caribbean,Upper middle income,12.604193,13.682946,13.009381,11.802358,12.230920,12.598774,13.856941,15.089966

In [6]:
import pandas as pd

new_path = "carbon_tax_price.csv"
new_df = pd.read_csv(new_path)
# new_df.drop(columns=['Unnamed: 0'], inplace=True)
new_df.to_excel("carbon_tax_price.xlsx", index=False)